export const COMMON = {
  PROJECT_NAME: 'THOMAS WEB',
  OK_BTN: 'OK',
  TITLE_JOIN_PIPE: '∣',
  CONFIRM: '確認',
  HOME: 'ホーム',
  MYFAVORITES: 'お気に入り',
};
export const LOGIN = {
  USERID: 'ユーザーID',
  PASSWORD: 'パスワード',
  LOGIN_BTN: 'ログイン',
  LOGOUT_BTN: 'ログアウト',
};
export const REFERENCE_SCREEN = {
  TITLE: '参照画面',
};
export const REFERENCE_SETTING = {
  INITIAL_SEARCH_TITLE: '初期検索設定',
  INITIAL_SEARCH_LABEL: '初期値で検索',
  RADIO_OPTION_YES: 'する',
  RADIO_OPTION_NO: 'しない',
};
export const FILTER_TEXT = {
  SEARCH_BTN: '検索',
  RESET_BTN: '条件初期化',
  COND_SET_BTN: '条件設定',
  CHECKBOX_ALL_OPTION: 'すべて',
  FILTER_MATCH_CONDITIONS: {
    RANGE: '〜',
    EQ: 'と等しい', //equals
    NEQ: 'と等しくない', //not equals
    SW: 'で始まる', //starts with
    NSW: 'で始まらない', //not starts with
    EW: 'で終わる', //end with
    NEW: 'で終わらない', //not ends with
    CON: 'を含む', //contains
    NCON: 'を含まない', //not contains
    IN: 'が空白', //is null
    INN: 'が空白でない', //is not null
  },
};
export const GRID_TEXT = {
  FILTER_RESET: 'Clear',
  ADD_ROW: '追加',
  DELETE_ROW: '削除',
  COPY_ROW: 'コピー',
  ADD_DATA: '新規',
  EDIT_DATA: '修正',
  STATUS: 'ステータス',
  SAVE_BTN: '更新',
  CANCEL_BTN: 'キャンセル',
  APPLY_BTN: '適用',
};
export const CONDITION_SETTING_DISP = {
  TITLE: '条件設定表示',
  NAME: '名称',
  ACCESS_TYPE: '公開範囲',
  ACCESS_TYPE_OPTIONS: ['個人用', '公開用'],
  REG_USERS: '登録ユーザー ',
  LOAD_TAB: '読込',
  SAVE_TAB: '保存',
  SEARCH_BTN: '検索',
  RESET_BTN: '条件初期化',
  SAVE_BTN: '更新',
  INITIAL_DATA: '既定値に戻す',
  DELETE_TLTIP: '削除',
  EDIT_TLTIP: '編集',
  PREVIEW_TLTIP: '表示',
};
export const AUTOMATIC_HEIGHT_ADJUSTMENT = {
  TITLE: '自動調整表示',
  LABEL: '高さ自動調節',
  YES: 'する',
  NO: 'しない',
  OK: 'OK',
  CANCEL: 'キャンセル',
};
export const CELL_SELECTION = {
  CELL_SUMMARY_BTN: 'ステータス',
  CELL_MODE: 'セルモード',
  AVERAGE: '平均',
  NUM_DATA: 'データの個数',
  NUM_VALUES: '数値の個数',
  MIN: '最小値',
  MAX: '最大値',
  SUM: '合計',
};
export const HIDE_FILTERS_DAILOG = {
  TITLE: 'フィルター行表示',
  RADIO_OPTION_YES: 'する',
  RADIO_OPTION_NO: 'しない',
};
export const TABLE_OPTIONS = {
  TITLE: '表オプション',
  EXPORT: '名前を付けて保存',
  SORT_DATA: 'データ並替',
  SWAP_COLUMNS: '列の入替',
  DISPLAY_FILTER: 'フィルター行設定',
};
export const EXPORT = {
  LABEL: 'ファイル名',
  DOWNLOAD: 'ダウンロード',
  DEFAULT_FILE_NAME: 'トーマス_データ',
};
export const SORT_DATA = {
  LABEL: 'データの並べ替え',
  NONE_SELECTED_OPTION: '(指定無し)',
  ASCENDING: '昇進',
  DESCENDING: '降順',
  SORT: '並べ替え',
  RESET_BTN: 'リセット',
};
export const SWAP_COLUMNS = {
  DIALOG_TITLE: '列の入れ替え',
  HEADER_COLUMN: 'カラム列',
  HEADER_Display: '表示',
  HEADER_FIXED_COLUMNS: '列固定',
  BTN_TEXT_INITIAL_DATA: '既定値に戻す',
  BTN_TEXT_OK: 'OK',
};
export const UPLOAD_IMAGES = {
  SELECT_FILES_BTN: 'ファイルを選択',
  HEADER_TEXT: 'ファイル一覧',
  APPLY_BTN: '適用',
};
export const TOROKU = {
  REF: '参照',
  UPDATE: '編集',
  ADD: '新規',
  EDIT: '修正',
  COPY: 'コピー',
  DELETE_BTN: '削除',
  BACK: '戻る',
  OPEN_SAME: '同じタブで開く',
  OPEN_TAB: '新しいタブで開く',
  OPEN_WINDOW: '新しいウィンドウで開く',
  YES: 'はい',
  NO: 'いいえ',
  CANCEL: 'キャンセル',
  SAVE_BTN: '更新',
  RESET_BTN: 'リセット',
};
export const MITEM0010I = {
  FORM_ID: 'MITEM0010I',
  FORM_TITLE: '品目情報 1',
  ITEMCD: '品目コード',
  ITEMNM: '品目名称',
  PRODUCTCD: '製品コード',
  PRODUCTNM: '製品名',
  PRODUCTENM: '製品の英語名',
  PRODUCTNO: '製品品番',
  MultiColumn: '名称検索',
  HMNM: '品目名称',
  HMRNM: '品目略称',
  WEBITEMCD: 'ＷＥＢ品番',
  JANCD: 'ＪＡＮコード',
  ITEMTYP: '品番種類',
  ITEMTYP_OPTIONS: [
    '標準品',
    '追加工サービス品',
    '追加工サービス拡張品',
    '特殊品',
    'その他',
    '追加工代表コード',
  ],
  VALSTARTYMD: '有効開始日',
  REFITEMCD: '参照品目コード',
  ORGITEMCD: '材料品目コード',
  PRICEITEMCD: '価格参照品目コード',
};
export const MITEM0010U = {
  FORM_ID: 'MITEM0010U',
  FORM_TITLE: '品目一覧',
  ITEMCD: '品目コード',
  ITEMNM: '品目名称',
  PRODUCTCD: '製品コード',
  PRODUCTNM: '製品名',
  PRODUCTENM: '製品の英語名',
  PRODUCTNO: '製品品番',
  MultiColumn: '名称検索',
  HMNM: '品目名称',
  HMRNM: '品目略称',
  WEBITEMCD: 'ＷＥＢ品番',
  JANCD: 'ＪＡＮコード',
  ITEMTYP: '品番種類',
  ITEMTYP_OPTIONS: [
    '標準品',
    '追加工サービス品',
    '追加工サービス拡張品',
    '特殊品',
    'その他',
    '追加工代表コード',
  ],
  VALSTARTYMD: '有効開始日',
  REFITEMCD: '参照品目コード',
  ORGITEMCD: '材料品目コード',
  PRICEITEMCD: '価格参照品目コード',
};
export const MITEM0011U = {
  FORM_TITLE: '品目登録 1',
  FORM_ID: 'MITEM0011U',
  ITEMCD: '品目コード',
  ITEMNM: '品目名称',
  PRODUCTCD: '製品コード',
  PRODUCTNM: '製品名',
  PRODUCTENM: '製品の英語名',
  PRODUCTNO: '製品品番',
  MultiColumn: '名称検索',
  HMNM: '品目名称',
  HMRNM: '品目略称',
  WEBITEMCD: 'ＷＥＢ品番',
  JANCD: 'ＪＡＮコード',
  ITEMTYP: '品番種類',
  ITEMTYP_OPTIONS: [
    '標準品',
    '追加工サービス品',
    '追加工サービス拡張品',
    '特殊品',
    'その他',
    '追加工代表コード',
  ],
  VALSTARTYMD: '有効開始日',
  REFITEMCD: '参照品目コード',
  ORGITEMCD: '材料品目コード',
  PRICEITEMCD: '価格参照品目コード',
  YES_BTN: 'する',
  NO_BTN: 'しない',
  CANCEL_BTN: 'キャンセル',
};
export const A0015U = {
  FORM_TITLE: '品目登録 2',
  FORM_ID: 'A0015U',
  KIHONJOHO: '基本情報',
  KOSEIJOHO: '構成情報',
  KOJUNJOHO: '工順情報',
  HMNO: '品目コード',
  HMNM: '品目名称',
  ARRGKBN: '基準手配区分',
  ARRGKBN_OPTIONS: {
    1: '工程',
    2: '購買',
  },
  PLANKBN: '計画区分',
  PLANKBN_OPTIONS: {
    1: '在庫補充（MPS）',
    2: '紐付き生産（受注・計画）',
  },
  MRSTOCKQTY: 'まるめ数量',
  MINSTOCKQTY: '最小手配数量',
  MANSTOCKQTY: '最大手配数量',
  UNIT: '計量単位コード',
  OYAHMNO: '親品目コード',
  KOHMNO: '子品目コード',
  YMDFR: '有効開始日',
  YMDTO: '有効終了日',
  STRSEQ: '順序NO',
  OYAQTY: '員数分母',
  KOQTY: '員数分子',
  KOUNIT: '員数分子単位',
  BADRATE: '不良率(%)',
  STOCKCD: '引落在庫場所コード',
  PROCESEQ: '工順',
  PROCECD: '工程コード',
  IOKBN: '内外作区分',
  IOKBN_OPTIONS: {
    1: '社内',
    2: '外注',
  },
  SUPPCD: '仕入先コード',
  RESCD: '資源コード',
  MVLT: '移動L/T',
  CAPVAL: '能力',
  CAPUNIT: '能力単位',
  CAPUNIT_OPTIONS: {
    1: '日',
    2: '分',
  },
  CAPQTY: '個数（計量単位）',
  PRESETUP: '前段階時間(分)',
  AFTSETUP: '後段取時間(分)',
  PRESETUPKBN: '前段階稼働時間区分',
  PRESETUPKBN_OPTIONS: {
    1: '稼働時間内',
    2: '24時間',
  },
  AFTSETUPKBN: '後段階稼働時間区分',
  AFTSETUPKBN_OPTIONS: {
    1: '稼働時間内',
    2: '24時間',
  },
  PLANTMKBN: '生産時間区分',
  PLANTMKBN_OPTIONS: {
    1: '稼働時間内',
    2: '24時間',
  },
  WITHINWKTM_PRESETUP: '稼働時間内_前段階時間(分)',
  WITHINWKTM_AFTSETUP: '稼働時間内_後段階時間(分)',
  WITHINWKTM_PRODSTART: '稼働時間内_製造開始時間(分)',
  JISSEKIKBN: '実績登録必須区分',
  JISSEKIKBN_OPTIONS: {
    1: '必須',
    2: '任意',
    3: '不要',
  },
};

export const A103 = {
  FORM_ID: 'M_ITEM001',
  FORM_TITLE: '品目マスタ',
  HMNO: '品目コード',
  HMNM: '品目名称',
  MRSTOCKQTY: 'まるめ数量',
  MINSTOCKQTY: '最小手配数量',
  MANSTOCKQTY: '最大手配数量',
  UNIT: '計量単位コード',
  UNITNM: '単位名称',
  ARRGKBN: '基準手配区分',
  PLANKBN: '計画区分',
  STOCKKBN: '在庫管理区分',
  ARRSTOCKCD: '入荷保管場所コード',
  ARRSTOCKNM: '入荷保管場所名称',
  MFGSTOCKCD: '製造保管場所コード',
  MFGSTOCKNM: '製造保管場所名称',
  USEDSTOCKCD: '使用保管場所コード',
  USEDSTOCKNM: '使用保管場所名称',
  STOCKTYPEKBN: '在庫管理タイプ区分',
  KEEPSTOCKKBN: '安全在庫区分',
  KEEPSTOCK: '安全在庫',
  MERGEINTERVAL: '出庫まとめ期間(日)',
  ARRGKBN_options: ['工程', '購買'],
  PLANKBN_options: ['在庫補充（MPS）', '紐付き生産（受注・計画）'],
  STOCKKBN_options: ['する', 'しない'],
  STOCKTYPEKBN_options: [
    'ロット/Batch管理',
    'Seraial管理',
    'Batch',
    'Serial無し',
  ],
  KEEPSTOCKKBN_options: ['数量', '日数'],
  STATE_options: ['利用可能', '検査中', '保留'],
  SHELFFLG_options: ['する', 'しない'],
};

export const A104 = {
  FORM_ID: 'M_ITEM002',
  FORM_TITLE: '品目構成マスタ',
  OYAHMNO: '親品目コード',
  OYAHMNM: '親品目名称',
  KOHMNO: '子品目コード',
  KOHMNM: '子品目名称',
  YMDFR: '有効開始日',
  YMDTO: '有効終了日',
  STRSEQ: '順序NO',
  OYAQTY: '員数分母',
  KOQTY: '員数分子',
  KOUNIT: '員数分子単位',
  UNITNM: '単位名称',
  BADRATE: '不良率(%)',
};

export const A105 = {
  FORM_ID: 'M_ITEM003',
  FORM_TITLE: '品目工順情報',
  HMNO: '品目コード',
  HMNM: '品目名称',
  PROCESEQ: '工順',
  PROCECD: '工程コード',
  PROCENM: '工程名称',
  IOKBN: '内外作区分',
  SUPPCD: '仕入先コード',
  BCNM: '仕入先名称',
  SUPPSTOCKCD: '仕入先保管場所コード',
  STOCKNM: '仕入先保管場所名称',
  RESCD: '資源コード',
  RESNM: '資源名称',
  MVLT: '移動L/T',
  CAPVAL: '能力',
  CAPUNIT: '能力単位',
  CAPQTY: '個数（計量単位）',
  PRESETUP: '前段階時間(分)',
  AFTSETUP: '後段取時間(分)',
  PRESETUPKBN: '前段階稼働時間区分',
  AFTSETUPKBN: '後段階稼働時間区分',
  PLANTMKBN: '生産時間区分',
  WITHINWKTM_PRESETUP: '稼働時間内_前段階時間(分)',
  WITHINWKTM_AFTSETUP: '稼働時間内_後段階時間(分)',
  WITHINWKTM_PRODSTART: '稼働時間内_製造開始時間(分)',
  JISSEKIKBN: '実績登録必須区分',
  IOKBN_options: ['社内', '外注'],
  CAPUNIT_options: ['日', '分'],
  PRESETUPKBN_options: ['稼働時間内', '24時間'],
  AFTSETUPKBN_options: ['稼働時間内', '24時間'],
  PLANTMKBN_options: ['稼働時間内', '24時間'],
  JISSEKIKBN_options: ['必須', '任意', '不要'],
  STATE_options: ['利用可能', '検査中', '保留'],
  SHELFFLG_options: ['する', 'しない'],
  //参照
  MPROC007: '保管場所マスタ',
  REF_STOCKCD: '保管場所コード',
  REF_STOCKNM: '保管場所名称',
  REF_STATE: 'ステータス区分',
  REF_MEMO: 'メモ',
  REF_SHELFFLG: '棚番管理フラグ',
  MPROC001: '工程マスタ',
  MCUST001: '取引先マスタ',
  REF_BCCD: '取引先コード',
  REF_BCNM: '取引先名称',
  MRES001: '資源マスタ',
};
export const C105 = {
  FORM_ID: 'C105',
  FORM_TITLE: '作業指示承認',
  KAKUTEIKBN: '確定',
  PRESETUPSTARTDT: '着手日時',
  HMNO: '品目コード',
  HMNM: '品目名称',
  PLANSTOCKQTY: '入庫予定数',
  FRPROCECD: '初工程コード',
  FRPROCENM: '初工程名称',
  TOPROCECD: '最終工程コード',
  TOPROCENM: '最終工程名称',
  FRRESCD: '初工程資源コード',
  FRRESNM: '初工程資源名称',
  TORESCD: '最終工程資源コード',
  TORESNM: '最終工程資源名称',
  PLANSTOCKDTM: '入庫予定日時',
  NEXTLINKPLANNO: '次紐づけ生産指示番号',
  JORDERNO: '受注オーダーNO',
  FRIOKBN: '初工程内外作区分',
  FRIOKBN_OPTIONS: ['社内', '社外'],
  TOIOKBN: '最終工程内外作区分',
  TOIOKBN_OPTIONS: ['社内', '社外'],
  PLANNO: '指示番号',
  REF_COL_PROCECD: '工程コード',
  REF_COL_PROCENM: '工程名称',
  REF_COL_RESCD: '資源コード',
  REF_COL_RESNM: '資源名称',
  SYOUNIN: '承認',
};
export const D103 = {
  FORM_ID: 'D103',
  FORM_TITLE: '作業指示参照',
  PLANNO: '指示番号',
  PROCESEQ: '工順',
  STATE: '状態',
  HMNO: '品目コード',
  HMNM: '品目名称',
  RESCD: '資源',
  PROCECD: '工程',
  PLANQTY: '計画数量',
  NEEDQTY: '必要数量',
  YIELDQTY: '歩留数量',
  PRESETUPSTARTDT: '前段取開始日時',
  PRODSTARTDT: '製造開始日時',
  PRODENDDT: '製造終了日時',
  AFTSETUPENDDT: '後段取終了日時',
  ACTUALQTY: '使用数量',
  KOHMNO: '使用品目コード',
  KOHMNM: '使用品目名称',
  BACK_TO_LIST_BTN: '戻る',
};
export const D101 = {
  FORM_ID: 'D101',
  FORM_TITLE: '作業指示確認',
  PRESETUPSTARTDT: '前段取開始日時',
  PRODSTARTDT: '製造開始日時',
  PRODENDDT: '製造終了日時',
  AFTSETUPENDDT: '後段取終了日時',
  HMNO: '品目コード',
  HMNM: '品目名称',
  PLANQTY: '計画数量',
  NEEDQTY: '必要数量',
  YIELDQTY: '歩留数量',
  PROCECD: '工程コード',
  PROCENM: '工程名称',
  IOKBN: '内外作区分',
  IOKBN_OPTIONS: ['内作', '外作'],
  RESCD: '資源コード',
  RESNM: '資源名称',
  ACTUALDT: '製造完了日時',
  ACTUALQTY: '製造数量',
  GOODQTY: '出来高数量',
  BADQTY: '不良数量',
  PLANNO: '指示番号',
  PROCESEQ: '工順',
  MFGSTATE: '製造状態',
  MFGSTATE_OPTIONS: ['未着手', '製造中', '完了', '中止'],
  STATE: '状態',
  STATE_OPTIONS: [
    '未着手',
    '前段取中',
    '前段取中断中',
    '前段取休憩中',
    '製造中',
    '製造中断中',
    '製造休憩中',
    '作業引継中',
    '後段取中',
    '後段取休憩中',
    '完了',
  ],
  PRVSTATE: 'PRVSTATE',
  REF_COL_PROCECD: '工程コード',
  REF_COL_PROCENM: '工程名称',
  REF_COL_RESCD: '資源コード',
  REF_COL_RESNM: '資源名称',
  BTN_Move_D201: '製造実施',
  BTN_Move_D205: '外注受入',
  BTN_Move_D103: '作業指示参照',
  move_Work_Instructions: '作業指示書発行',
};
export const D104 = {
  FORM_ID: 'D104',
  FORM_TITLE: '作業指示書発行',
  PLANNO: '指示番号',
  HMNO: '品目コード',
  HMNM: '品目名',
  PLANSTOCKDTM: '入庫予定日時',
  PLANSTOCKQTY: '入庫予定数',
  FRPROCECD: '初工程コード',
  FRPROCENM: '初工程名称',
  TOPROCECD: '最終工程コード',
  TOPROCENM: '最終工程名称',
  FRRESCD: '初工程資源コード',
  FRRESNM: '初工程資源名称',
  TORESCD: '最終工程資源コード',
  TORESNM: '最終工程資源名称',
  STATE: '製造状態',
  STATE_OPTIONS: ['未着手', '製造中', '完了', '中止'],
  QRCORD: 'QRコード',
  PROCECD: '工程コード',
  REF_COL_PROCECD: '工程コード',
  REF_COL_PROCENM: '工程名称',
  REF_COL_RESCD: '資源コード',
  REF_COL_RESNM: '資源名称',
  PRINTBTN: '印刷',
  PREVIEWBTN: 'プレビュー',
};

export const D201 = {
  FORM_ID: 'D201',
  FORM_TITLE: '製造実施',
  INSTRUCTIONS_TAB: '指示内容',
  SOP_TAB: 'SOP',
  CHECKLIST_TAB: 'チェックリスト',
  MNFG_DATA_INPUT_TAB: '製造データ入力',
  ITEMS_INPUT_TAB: '投入品目',
  MNFG_PERFORMANCE_INQUERY_TAB: '製造実績照会',
  HMNO: '品目コード',
  HMNM: '品目名称',
  PLANQTY: '計画数量',
  NEEDQTY: '必要数量',
  YIELDQTY: '歩留数量',
  CHARGECD: '担当者コード',
  CHARGENM: '担当者名称',
  PROCECD: '工程コード',
  PROCENM: '工程名称',
  RESCD: '資源コード',
  RESNM: '資源名称',
  STOCKCD: '保管場所コード',
  SHELFNO: '棚番',
  PRESETUPSTARTDT: '前段取開始日時',
  PRODSTARTDT: '製造開始日時',
  PRODENDDT: '製造終了日時',
  AFTSETUPENDDT: '後段取終了日時',
  PLANNO: '指示番号',
  PROCESEQ: '工順',
  GOODQTY: '出来高数',
  LOTNO: 'ロット番号',
  BADQTY: '不良数',
  REACD: '不良理由コード',
  REANM: '不良理由名称',
  STATE: '状態',
  LABELNO: '現品ラベル番号',
  USE_HMNO: '使用品目コード',
  USE_HMNM: '使用品目名称',
  STOCKQTY: '在庫数量',
  UNITNM: '単位',
  WORKKBN: '作業',
  WORKSTARTDT: '着手日付',
  WORKSTARTTM: '時刻',
  WORKENDDT: '完了日付',
  WORKENDTM: '時刻',
  WORKTIME: '小計',
  OPERATOR_LBL: '作業者',
  WORKSEQ: '作業順序NO',
  EDIT_JISSEKI_LBL: "製造実績修正",
  NEW_JISSEKI_LBL: "製造実績登録",
  CURRENTITEM_FULLYCONSUMED: '現品ラベル使い切り',
  CURRENTITEM_LABELNO: '現品ラベル番号',
  ACTUALQTY: '使用実績数',
  MANUFACTURING_NOTES: '製造備考',
  TOTALTIME_PRE: '前段取',
  TOTALTIME_RUN: '製造',
  TOTALTIME_POST: '後段取',
  TOTALTIME_BREAK: '休憩',
  TOTALTIME_PAUSE: '中断',
  TOTALTIME_ALL: '合計',
  SUMGOODQTY: '出来高数',
  SUMBADQTY: '不良数',
  MINUTES_LBL: '分',
  TOTAL_LBL: '合計',
  DETAILS_LBL: '明細',
  UNIT: '単位コード',
  LABELDTTM: '現品ラベル入庫日',
  STATE_1: '未着手', // Not Started
  STATE_2: '前段取中', // Pre-Setup in Progress
  STATE_3: '前段取中断中', // Pre-Setup Interrupted
  STATE_4: '前段取休憩中', // Pre-Setup on Break
  STATE_5: '製造中', // In Production
  STATE_6: '製造中断中', // Production Interrupted
  STATE_7: '製造休憩中', // Production on Break
  STATE_8: '作業引継中', // Work Handover in Progress
  STATE_9: '後段取中', // Post-Setup in Progress
  STATE_A: '後段取休憩中', // Post-Setup on Break
  STATE_B: '完了', // Completed
  /*NOT_STARTED_ST: '未着手', // Not Started
  PRESETUP_PROGRESS_ST: '前段取中', // Pre-Setup in Progress
  PRESETUP_INTERRUPT_ST: '前段取中断中', // Pre-Setup Interrupted
  PRESETUP_ONBREAK_ST: '前段取休憩中', // Pre-Setup on Break
  PRODUCTION_PROGRESS_ST: '製造中', // In Production
  PRODUCTION_INTERRUPT_ST: '製造中断中', // Production Interrupted
  PRODUCTION_ONBREAK_ST: '製造休憩中', // Production on Break
  HANDOVER_PROGRESS_ST: '作業引継中', // Work Handover in Progress
  POSTSETUP_PROGRESS_ST: '後段取中', // Post-Setup in Progress
  POSTSETUP_ONBREAK_ST: '後段取休憩中', // Post-Setup on Break
  COMPLETED_ST: '完了', // Completed*/
  START_SETUP_BTN: '段取開始', // Start setup
  START_PRODUCTION_BTN: '製造開始', // Begin manufacturing
  END_PRODUCTION_BTN: '製造終了', // End manufacturing
  END_POST_SETUP_BTN: '後段取終了', // End post-setup stage
  PRODUCTION_HANDOVER_BTN: '製造引継ぎ', // Handover production process
  HANDOVER_COMPLETE_BTN: '引継ぎ完了', // Handover complete
  INTERRUPT_BTN: '中断', // Interrupt the process
  RESUME_BTN: '再開', // Resume after interruption
  START_BREAK_BTN: '休憩開始', // Start break
  END_BREAK_BTN: '休憩終了', // End break
  CANCEL_BTN: '開始取消', // Cancel operation
  BACK_TO_LIST_BTN: '一覧に戻る', // Return to list view
  CHECKLIST_HEADER: 'チェック内容',
  CHECKLIST_NOTE: '備考',
  MEASUREMENT_HEADER: '測定項目',
  REGISTER_BTN: '登録',
  RESULT_TAB_GRID_EXTRA_BTN: '修正ボタン',
  JISSEKI_REGISTER_BTN: '実績登録',
  BACK_BTN: '戻る',
  TIMES_LABEL: '回目',
  COMPLETE_LABEL: '完了',
  TOROKUSHA: '登録者',
  INCHARGE: '担当者',
  // used for status update events
  ProcessingEvents: {
    START_PRE_SETUP: '前段取開始',
    START_PRODUCTION: '製造開始',
    INTERRUPT_PRODUCTION: '中断',
    RESUME_FROM_INTERRUPT: '中断再開',
    START_BREAK: '休憩開始',
    RETURN_FROM_BREAK: '休憩戻り',
    RESUME_AFTER_HANDOVER: '引継再開',
    CANCEL_START: '開始取消',
    END_POST_PROCESS: '後段取終了',
  },
  // used to know which button got us to result reference registration
  ProcessingBtn: {
    END_PRODUCTION_BTN: '製造終了',
    START_BREAK_BTN: '休憩開始',
    INTERRUPT_BTN: '中断',
    EDIT_MODE: '修正',
    PRODUCTION_HANDOVER_BTN: '作業引継',
  },
  WORKKBN_OPTIONS: ['前段取', '製造', '後段取', '休憩', '中断'],
  NO_BTN: 'しない',
  DIALOG_CANCEL_BTN: 'キャンセル',
};
export const D204 = {
  FORM_ID: 'D204',
  FORM_TITLE: '完成品現品ラベル発行',
  PRESETUPSTARTDT: '前段取開始日時',
  PRODSTARTDT: '製造開始日時',
  PRODENDDT: '製造終了日時',
  AFTSETUPENDDT: '後段取終了日時',
  HMNO: '品目コード',
  HMNM: '品目名称',
  CHARGECD: '担当者コード',
  CHARGENM: '担当者名称',
  PROCECD: '工程コード',
  PROCENM: '工程名称',
  RESCD: '資源コード',
  RESNM: '資源名称',
  STOCKCD: '保管場所コード',
  STOCKNM: '保管場所名称',
  SHELFNO: '棚番',
  LABELNO: '現品ラベル番号',
  LOTNO: 'ロット番号',
  ACTUALDT: '製造完了日時',
  ACTUALQTY: '製造数量',
  GOODQTY: '出来高数量',
  BADQTY: '不良数量',
  PLANNO: '指示番号',
  PROCESEQ: '工順',
  REF_COL_PROCECD: '工程コード',
  REF_COL_PROCENM: '工程名称',
  REF_COL_RESCD: '資源コード',
  REF_COL_RESNM: '資源名称',
  STOCKQTY: '在庫数量',
  UNIT: '単位コード',
  UNITNM: '単位名称',
  PRINTBTN: '印刷',
  PREVIEWBTN: 'プレビュー',
};
export const D205 = {
  FORM_ID: 'D205',
  FORM_TITLE: '外注受入実績登録',
  HMNO: '品目コード',
  HMNM: '品目名称',
  CHARGECD: '担当者コード',
  CHARGENM: '担当者名称',
  PROCECD: '工程コード',
  PROCENM: '工程名称',
  RESCD: '資源コード',
  RESNM: '資源名称',
  STOCKCD: '保管場所コード',
  STOCKNM: '保管場所名称',
  SHELFNO: '棚番',
  LABELNO: '現品ラベル番号',
  LOTNO: 'ロット番号',
  BADQTY: '不良数',
  REACD: '不良理由コード',
  REANM: '不良理由名称',
  PLANNO: '指示番号',
  PROCESEQ: '工順',
  STOCKQTY: '在庫数量',
  UNIT: '単位コード',
  UNITNM: '単位名称',
  PRINTBTN: '印刷',
  PREVIEWBTN: 'プレビュー',
  REGISTER_BTN: '登録',
  BACK_BTN: '戻る',
  JISSEKI_REGISTER_BTN: '実績登録',
  BACK_TO_LIST_BTN: '一覧に戻る', // Return to list view
  ORDERQTY: '入荷数量',
  ORDERUNIT: '入荷単位',
  PRICE: '入荷単価',
  ODRAMOUNT: '入荷金額',
  BCNM: '仕入先',
  FLG: '入荷完了',
};
export const C101 = {
  FORM_ID: 'C101',
  FORM_TITLE: '作業指示確定',
  KAKUTEIKBN: '確定',
  PRESETUPSTARTDT: '着手日時',
  HMNO: '品目コード',
  HMNM: '品目名称',
  PLANSTOCKQTY: '入庫予定数',
  FRPROCECD: '初工程コード',
  FRPROCENM: '初工程名称',
  TOPROCECD: '最終工程コード',
  TOPROCENM: '最終工程名称',
  FRRESCD: '初工程資源コード',
  FRRESNM: '初工程資源名称',
  TORESCD: '最終工程資源コード',
  TORESNM: '最終工程資源名称',
  PLANSTOCKDTM: '入庫予定日時',
  NEXTLINKPLANNO: '次紐づけ生産指示番号',
  JORDERNO: '受注オーダーNO',
  FRIOKBN: '初工程内外作区分',
  FRIOKBN_OPTIONS: ['社内', '社外'],
  TOIOKBN: '最終工程内外作区分',
  TOIOKBN_OPTIONS: ['社内', '社外'],
  PLANNO: '指示番号',
  REF_COL_PROCECD: '工程コード',
  REF_COL_PROCENM: '工程名称',
  REF_COL_RESCD: '資源コード',
  REF_COL_RESNM: '資源名称',
  UPDATE_TITLE: '確定',
};

export const C110 = {
  FORM_ID: 'C110',
  FORM_TITLE: '注文書発行',
  PLANNO: '指示番号',
  HMNO: '品目コード',
  HMNM: '品目名',
  PROCECD: '工程コード',
  PROCENM: '工程名称',
  SUPPCD: '仕入先コード',
  BCNM: '仕入先名称',
  DELIVERYDT: '納期',
  ORDERQTY: '発注数量',
  ORDERUNIT: '発注T単位',
  UNITNM: '発注単位名称',
  PRICE: '発注単価',
  ODRAMOUNT: '発注金額',
  REMARK: '備考',
  PRINTBTN: '印刷',
  PREVIEWBTN: 'プレビュー',
};

export const B110 = {
  FORM_ID: 'B110',
  FORM_TITLE: 'MPS処理',
  FORM_INFO_LABLE: 'S&OP情報を元にMPS処理を実行します。',
  MPS_PROCESS_ERROR_LABLE: 'MPS処理が完了しましたが、エラーがありました。',
  DATE_LABLE: '実行日時',
  EXECUTOR_LABLE: '実行者',
  Save_Button: '実行',
  SEQ: 'SEQ',
  ERROR_ID: 'エラーID',
  ERROR_CATEGORY: 'エラー区分',
  ERROR_LOCATION: 'エラー箇所',
  MESSAGE: 'メッセージ',
  ERRKBN_OPTIONS: ['警告', '情報'],
};

export const F101 = {
  FORM_ID: 'F101',
  FORM_TITLE: '在庫推移照会',
  FROM_DATE: '基準日',
  DAYS: '日間',
  HMNO: '品目',
  HINMOKU_JOKEN_KBN: '品目条件区分',
  HINMOKU_JOKEN_KBN_OPTIONS: ['通常条件', '構成下位展開', '構成上位展開'],
};
export const F102 = {
  FORM_ID: 'F102',
  FORM_TITLE: '材料現品ラベル発行',
  PRESETUPSTARTDT: '前段取開始日時',
  PRODSTARTDT: '製造開始日時',
  PRODENDDT: '製造終了日時',
  AFTSETUPENDDT: '後段取終了日時',
  HMNO: '品目コード',
  HMNM: '品目名称',
  CHARGECD: '担当者コード',
  CHARGENM: '担当者名称',
  PROCECD: '工程コード',
  PROCENM: '工程名称',
  RESCD: '資源コード',
  RESNM: '資源名称',
  STOCKCD: '保管場所コード',
  STOCKNM: '保管場所名称',
  SHELFNO: '棚番',
  LABELNO: '現品ラベル番号',
  LOTNO: 'ロット番号',
  ACTUALDT: '製造完了日時',
  ACTUALQTY: '製造数量',
  GOODQTY: '出来高数量',
  BADQTY: '不良数量',
  PLANNO: '指示番号',
  PROCESEQ: '工順',
  REF_COL_PROCECD: '工程コード',
  REF_COL_PROCENM: '工程名称',
  REF_COL_RESCD: '資源コード',
  REF_COL_RESNM: '資源名称',
  STOCKQTY: '在庫数量',
  UNIT: '単位コード',
  UNITNM: '単位名称',
  PRINTBTN: '印刷',
  PREVIEWBTN: 'プレビュー',
};
