export const PRIMENG_JA_TRANSLATIONS = {
  today: '今日',
  clear: 'クリア',
  apply: '適用',
  dateFormat: 'yy/mm/dd', // Date format in Japanese style
  firstDayOfWeek: 0, // Set Sunday as the first day of the week
  dayNamesMin: ['日', '月', '火', '水', '木', '金', '土'], // Days of the week in Japanese
  monthNames: [
    '1月',
    '2月',
    '3月',
    '4月',
    '5月',
    '6月',
    '7月',
    '8月',
    '9月',
    '10月',
    '11月',
    '12月',
  ],
  monthNamesShort: [
    '1月',
    '2月',
    '3月',
    '4月',
    '5月',
    '6月',
    '7月',
    '8月',
    '9月',
    '10月',
    '11月',
    '12月',
  ],
  startsWith: 'で始まる',
  contains: 'を含む',
  notContains: 'を含まない',
  endsWith: 'で終わる',
  equals: 'と等しい',
  notEquals: 'と等しくない',
  in: 'In',
  lt: 'より小さい',
  lte: '以下',
  gt: 'より大きい',
  gte: '以上',
  between: '～の間',
  is: 'Is',
  isNot: 'Is not',
  before: 'Before',
  after: 'After',
  dateIs: 'と等しい',
  dateIsNot: 'と等しくない',
  dateBefore: '指定日以前',
  dateAfter: '指定日以降',
  matchAll: 'すべて一致',
  matchAny: 'いずれか一致',
  addRule: 'ルール追加',
  removeRule: 'ルール削除',
  accept: 'はい',
  reject: 'いいえ',
};
