export const JPTEXT = {
  PROJECT_NAME: 'THOMASWEBフレームワーク',
  A0040U_TITLE: '品目基本情報',
  A0060U_TITLE: '品目発注情報',
  USERID: 'ユーザーID',
  PASSWORD: 'パスワード',
  CONFIRM_DIALOG_TITLE: '確認',
  SHINKI: '新規',
  SHUSEI: '修正',
  HMNO: '品目コード',
  HMNM: '品目名称',
  HMRNM: '品目略称',
  HMKBN: '品目区分',
  HMKBN_OPTIONS_1: '製品',
  HMKBN_OPTIONS_2: '仕掛品',
  HMKBN_OPTIONS_3: '材料',
  HMKBN_OPTIONS_4: '副資材',
  HMKBN_OPTIONS_5: '部品',
  SUPPCD: '仕入先コード',
  CUSTHMNM: '発注品名',
  CUSTUNIT: '発注単位コード',
  REFERENCE_SCREEN: '参照画面',
  MENU:{
    TITLE: 'メニュー'
  },
  BTN_TEXT: {
    BACKTOMENU: 'メニューに戻る',
    LOGOUT: 'ログアウト',
    LOGINBTN: 'ログイン',
    SAVEBTN: '更新',
    RESETBTN: 'レセット',
    SEARCH: '検索',
    CLEAR: '条件初期化',
    OK: 'OK',
    CANCEL: 'キャンセル',
    CONDITION_SETTING: '条件設定',
    CONDITION_SETTING_DISPLAY: '条件設定表示',
    AUTO_ADJUSTMENT_DISPLAY: '自動調整表示',
    HIDE_FILTERS_DISPLAY: 'フィルター行設定',
    AUTO_ADJUSTMENT: '自動調整',
    LOAD_TAB: '読込',
    SAVE_TAB: '保存',
    PREVIEW: 'Preview',
    INITIAL_DATA: '既定値に戻す',
    CELL_SUMMARY: 'ステータス',
    DOWNLOAD: 'ダウンロード',
    EDITABLE_GRID_BUTTON: {
      SAVE: '保存',
      ADD_ROWS: '行追加',
      DELETE_ROWS: '行削除',
      COPY_ROWS: '行コピー',
      PASTE_ROWS: '行貼付',
    },
    SELECTALL: '全選択',
    YES: 'はい',
    NO: 'いいえ',
    HIDE: '非表示',
    SHOW: '表示',
    MORE: 'その他'
  },
  TOOLTIP_TEXT: {
    DELETE: '削除',
    EDIT: '編集',
    PREVIEW: '表示',
  },
  MATCH_CONDITIONS: {
    range: '〜',
    equals: 'と等しい',
    notEquals: 'と等しくない',
    startsWith: 'で始まる',
    notStartsWith: 'で始まらない',
    endsWith: 'で終わる',
    notEndsWith: 'で終わらない',
    contains: 'を含む',
    notContains: 'を含まない',
    isNull: 'が空白',
    isNotNull: 'が空白でない',
    greaterThan: 'より大きい',
    lessThan: 'より小さい',
  },
  CELL_SELECTION_OPTNS: {
    CELL_MODE: 'セルモード',
    AVERAGE: '平均',
    NUM_DATA: 'データの個数',
    NUM_VALUES: '数値の個数',
    MIN: '最小値',
    MAX: '最大値',
    SUM: '合計',
  },
  CONDITION_SETTING_DISP: {
    NAME: '名称',
    ACCESS_TYPE: '公開範囲',
    ACCESS_TYPE_OPTIONS: ['個人用', '公開用'],
    REG_USERS: '登録ユーザー ',
  },
  AUTOMATIC_HEIGHT_ADJUSTMENT_DIALOG: {
    TITLE: '高さ自動調節',
    RADIO_OPTION_YES: 'する',
    RADIO_OPTION_NO: 'しない',
  },
  HIDE_FILTERS_DAILOG:{
    TITLE: 'フィルター行表示',
    RADIO_OPTION_YES: 'する',
    RADIO_OPTION_NO: 'しない',
  },
  TABLE_OPTIONS: {
    TABLE_OPTIONS_TITLE: '表オプション',
    SAVE_AS: '名前を付けて保存',
    SORT_DATA: 'データ並替',
    SWAP_COLUMNS: '列の入替',
    SET_COLUMN_WIDTH: '列幅設定',
    ZOOM: 'ズーム',
    DISPLAY_FILTER : 'フィルター行設定',
  },
  SAVE_AS: {
    LABEL: 'ファイル名',
    DEFAULT_FILE_NAME: 'トーマス_データ',
  },
  SORT_DATA: {
    LABEL: 'データの並べ替え',
    NONE_SELECTED_OPTION: '(指定無し)',
    ASCENDING: '昇進',
    DESCENDING: '降順',
    SORT: '並べ替え',
  },
  REFERENCE_SETTING: {
    TITLE: '初期検索設定',
    LABEL: '初期検索で開く',
    RADIO_OPTION_YES: 'はい',
    RADIO_OPTION_NO: 'いいえ',
  },
  SWAP_COLUMNS: {
    DIALOG_TITLE: '列の入れ替え',
    HEADER_COLUMN: 'カラム列',
    HEADER_Display: '表示',
    HEADER_FIXED_COLUMNS: '列固定',
  },
  CELL_VALIDATIONS: {
    REQUIRED: '必要項目',
    INVALID_INPUT: '無効な入力',
  },
  TOROKU: {
    REF: '参照',
    UPDATE: '編集',
    ADD: '新規',
    EDIT: '修正',
    COPY : 'コピー',
    DELETE: '削除',
    BACK: '戻る',
    OPEN_SAME: '同じタブで開く',
    OPEN_TAB: '新しいタブで開く',
    OPEN_WINDOW: '新しいウィンドウで開く',
  },
  MITEM0010I: {
    FORM_ID: 'MITEM0010U',
    FORM_TITLE: '品目情報',
    ITEMCD: '品目コード',
    PRODUCTCD: '製品コード',
    PRODUCTNO: '製品品番',
    MultiColumn: '名称検索',
    HMNM: '品目名称',
    HMRNM: '品目略称',
    WEBITEMCD: 'ＷＥＢ品番',
    JANCD: 'ＪＡＮコード',
    ITEMTYP: '品番種類',
    ITEMTYP_OPTIONS: [
      '標準品',
      '追加工サービス品',
      '追加工サービス拡張品',
      '特殊品',
      'その他',
      '追加工代表コード',
    ],
    VALSTARTYMD: '有効開始日',
    REFITEMCD: '参照品目コード',
    ORGITEMCD: '材料品目コード',
    PRICEITEMCD: '価格参照品目コード',
    ITEMNM: '品目名称',
    PRODUCTNM: '製品名',
    PRODUCTENM: '製品の英語名',
  },
  MITEM0010U: {
    FORM_ID: 'MITEM0010U',
    FORM_TITLE: '品目情報一覧',
    ITEMCD: '品目コード',
    PRODUCTCD: '製品コード',
    PRODUCTNO: '製品品番',
    MultiColumn: '名称検索',
    HMNM: '品目名称',
    HMRNM: '品目略称',
    WEBITEMCD: 'ＷＥＢ品番',
    JANCD: 'ＪＡＮコード',
    ITEMTYP: '品番種類',
    ITEMTYP_OPTIONS: [
      '標準品',
      '追加工サービス品',
      '追加工サービス拡張品',
      '特殊品',
      'その他',
      '追加工代表コード',
    ],
    VALSTARTYMD: '有効開始日',
    REFITEMCD: '参照品目コード',
    ORGITEMCD: '材料品目コード',
    PRICEITEMCD: '価格参照品目コード',
    ITEMNM: '品目名称',
    PRODUCTNM: '製品名',
    PRODUCTENM: '製品の英語名',
  },
  M0010I: {
    FORM_ID: 'M0010I',
    FORM_TITLE: '品目基本情報画面',
    HMNO: '品目コード',
    HMNM: '品目名称',
    HMRNM: '品目略称',
    HMKBN: '品目区分',
    HMKBN_OPTIONS: {
      1: '製品',
      2: '仕掛品',
      3: '材料',
      4: '副資材',
      5: '部品',
      6: '経費',
    },
    CUSTCD: '基準得意先コード',
    CUSTHMNO: '基準客先品目NO',
    DRAWNO: '図面NO',
    SUPPCD: '基準仕入先コード',
    SECTIONCD: '基準仕入先コード',
    PROCECD: '基準工程コード',
    MCCD: '基準製造機械コード',
    CHARGECD: '出荷担当者コード',
    STOCKKBN: '在庫管理区分',
    STOCKKBN_OPTIONS: {
      1: '在庫管理する',
      2: '在庫管理しない',
    },
    STOCKHMNO: '在庫管理品目コード',
    STOCKCD: '基準在庫場所コード',
    LOTKBN: 'ロットNO管理区分',
    LOTKBN_OPTIONS: {
      1: '管理する',
      2: '管理しない',
    },
    YMDFR: '有効開始日付',
    YMDTO: '有効終了日付',
    PACKQTY: '梱包入り数',
    UNIT: '計量単位コード',
    WEIGHT: '重量',
    WEUNIT: '重量単位コード',
    WEDENUNIT: '重量分母単位コード',
    REMARK: '備考',
    ARRGKBN: '基準手配区分',
    ARRGKBN_OPTIONS: {
      1: '社内',
      2: '購買',
      3: '受給',
    },
    KSCD: '工種コード',
    YIELD: '内示受注歩留率',
    TPATARN: '内示受注展開パターン',
    TPATARN_OPTIONS: {
      1: '稼働日均等',
      2: '任意',
      3: '内示通り',
      4: '旬均等',
    },
    OFFSETKBN: '相殺区分',
    OFFSETKBN_OPTIONS: {
      1: '自動相殺しない',
      2: 'する',
    },
    OFFCUSTCD: '相殺得意先コード',
    USEKBN: '使用区分',
    USEKBN_OPTIONS: {
      1: '使用可',
      2: '使用不可',
    },
    INVOICENM: 'インボイス名称',
    TAXTYPE: '税タイプ',
    MASPROKBN: '量産区分',
    MASPROKBN_OPTIONS: {
      1: '量産',
      2: '試作',
      3: '仮',
    },
    CLASSCD: '品目分類コード',
    DECIKBN: '品目確定区分',
    DECIKBN_OPTIONS: {
      1: '月間',
      2: '週間',
      3: 'デイリー',
    },
    HMTYPEKBN: '品目種類',
    HMTYPEKBN_OPTIONS: {
      1: '標準品',
      2: '特殊品',
    },
    HMSEISENKBN: '品目生産方法',
    HMSEISENKBN_OPTIONS: {
      1: '在庫補充',
      2: '受注生産',
    },
    ZUBANNO: '図番',
    KAITEINO: '改訂No',
    SHIYO: '仕様',
    FEETQTY: '基準Feet数',
    LINKQTY: '基準リンク数',
    HINSHUCD: '品種コード',
    ZAISHITSUCD: '材質コード',
    ZAISHITSUSUNPO: '材質寸法',
    TANABAN: '棚番',
    SEIZOLOTQTY: '製造指示表ロット数',
    DANTORIKOUSU: '作業指示票用段取工数(分)',
    KOUSU: '作業指示票用工数(分)',
    KONPOUSAGYOUTM: '梱包作業時間(分)',
    JISSEKIKBN: '実績登録区分',
    JISSEKIKBN_OPTIONS: {
      1: 'する',
      2: 'しない',
    },
    SAGYOHYOIROKBN: '作業票色区分',
    SAGYOHYOIROKBN_OPTIONS: {
      0: '-',
      1: '白',
      2: '桃',
      3: '黄',
      4: '緑',
      5: '青',
      6: '橙',
    },
    KOSEIBUNRUIFLG: '構成展開分類区分',
    KOSEIBUNRUIFLG_OPTIONS: {
      1: 'JL',
      2: 'OL',
      9: 'ETC',
    },
    KOKUIN: '刻印',
    SHUYAKULT: '部品集約L/T',
    HINBANBIKOU: '品番コード備考',
    HINMEIBIKOU: '品名備考',
    SHIYOBIKOU: '仕様備考',
    ZUBANBIKOU: '図番備考',
    HENSEIGAEBIKOU: '編成替えメモ備考',
    HOJOBIKOU: 'メモ補助備考',
    BUHINKAKOUBIKOU1: '部品加工依頼票備考1',
    BUHINKAKOUBIKOU2: '部品加工依頼票備考2',
    JUYOYOSOKUTANIKBN: '需要予測単位区分',
    JUYOYOSOKUTANIKBN_OPTIONS: {
      1: 'Feet',
      2: '計量単位',
    },
    HMBUMONCD: '品目部門コード',
    KANSEIHMCD: '完成品目コード',
    DAIHYOHMCD: '代表品目コード',
    GMSAGYOKBN: 'GM作業区分',
    GMSAGYOKBN_OPTIONS: {
      1: '対象',
      2: '対象外',
    },
    SAGYOSHIJIHYOHINNM: '作業指示票表示名',
    KOBUHINKUMITATESAKI: '子部品組立先',
    ZAIRYONMHOJO: '材料名補助',
    HOJOBIKOU2: 'メモ補助備考2',
    PHANTOMKBN: 'ファントム区分',
    PHANTOMKBN_OPTIONS: {
      0: '通常',
      1: 'ファントム',
    },
    QTYKAKUHYOJIKBN: '半製品数量 各 表記区分',
    QTYKAKUHYOJIKBN_OPTIONS: {
      1: 'する',
      2: 'しない',
    },
    HANSAGYOHYOBIKOU1: '半製品指示票備考1',
    HANSAGYOHYOBIKOU2: '半製品指示票備考2',
    SAGYOSHIJIPRTKBN: '作業指示票発行対象区分',
    SAGYOSHIJIPRTKBN_OPTIONS: {
      0: '通常',
      1: '発行する',
    },
    EIGYOHINMEI: '在庫データ販売管理送信用品名',
    LINKQTYKBN: '基準リンク数区分',
    LINKQTYKBN_OPTIONS: {
      1: '数値',
      2: '計算式',
    },
    LINKQTYKEISANSHIKI: '基準リンク数計算式',
    HACHUBIKOU1: '発注用備考1',
    HACHUBIKOU2: '発注用備考2',
    HACHUBIKOU3: '発注用備考3',
    BUHINKAKOUKOUTEINM: '部品加工依頼票加工工程',
    HANSAGYOHYOHINMEI: '半製品票品名',
    HANSAGYOHYOHENSIYOU: '半製品票編成仕様',
    KOUSEITENKAIKBN: '構成展開方法区分',
    KOUSEITENKAIKBN_OPTIONS: {
      1: '通常',
      2: '特殊',
    },
    DEFAULTTEHAIKBN: '手配区分初期値',
    DEFAULTTEHAIKBN_OPTIONS: {
      2: '在庫',
      3: '在庫RN',
    },
    PLANPRICE: '計画原価',
    BUDOMARIQTY: '歩留まり',
    SLITMATERIALKBN: 'スリット加工材区分',
    SLIMMATERIALKBN_OPTIONS: {
      0: 'スリット加工材でない',
      1: 'スリット加工材',
    },
    GENKAHINSYU: '原価用品種コード',
    ZAIRYBUNNRUIKBN: '材料分類区分',
    ZAIRYBUNNRUIKBN_OPTIONS: {
      0: '-',
      1: '帯鋼',
      2: '板材',
      3: '線材',
      4: '丸棒',
      5: 'パイプ',
      6: 'ステンレス',
      7: 'アルミ',
      8: 'その他',
    },
    ZAIRYOKANKEIKBN: '原材料関係区分',
    ZAIRYOKANKEIKBN_OPTIONS: {
      0: '-',
      1: 'ローラーチェーン',
      2: 'コンベアチェーン',
    },
    SEIHINTEHAIKBN: '製品手配区分',
    SEIHINTEHAIKBN_OPTIONS: {
      0: '-',
      1: '自社',
      2: '外作',
      3: '仕入',
      4: '輸入',
      5: '購買',
    },
    SPKBN: 'スプロケット区分',
    SPKBN_OPTIONS: {
      0: '-',
      1: '受注スプロケット',
      2: '軸穴完成品スプロケット',
      3: 'カップリングチェン',
    },
    TANASYUKEIKBN: '仕掛品棚卸集計区分',
    TANASYUKEIKBN_OPTIONS: {
      1: '仕掛品棚卸集計内',
      2: '仕掛品棚卸集計外',
    },
    KOUJOUSIKIRI: '工場仕切',
    PBUNRUICD: '商品分類コード',
    LASTSALESQTY: '前期販売数',
    LASTSALESAMOUNT: '前期販売額',
    LATESTSHIPDATE: '最終出荷日',
    OTHEROUTKBN: 'その他出庫区分',
    OTHEROUTKBN_OPTIONS: {
      1: '通常',
      2: 'その他出庫',
    },
    BUHINHMNO: '集計用部品コード',
    COILKBN: 'コイル区分',
    COILKBN_OPTIONS: {
      0: 'コイル以外',
      1: 'コイル',
    },
    TOSTOCKCD: '材料払出先コード',
    TANAKESU: '棚卸係数',
    SEKUBN: '製品区分',
    SEKUBN_OPTIONS: {
      0: 'チェン',
      1: 'SP',
      2: '部品',
      3: 'その他',
    },
    LINKPRICE: 'リンク単価',
    UNITPRICE: 'ユニット単価',
    ZAIRYOHI: '材料費',
    COST: '製造原価',
    KANRICD: '管理コード',
    SEISANCD: '生産コード',
    HAKONO: '箱NO',
    IRISU: '入り数本',
    FTI10: '10FT入り数',
    FTG10: '10FT化粧箱',
    FTI5: '5FT',
    FTG5: '5FTG',
    MI5: '5M',
    MG5: '5MG',
    FTI50: '50FT入り数',
    FTG50: '50FTリール',
    FTI100: '100FT',
    FTG100: '100FTG',
    PLANBUNRUICD: '計画分類コード',
    JISSEKIBUNRUICD: '生産実績分類コード',
    ATTDAICD: 'ATT管理大分類コード',
    ATTCHUCD: 'ATT管理中分類コード',
    ATTSTOCKQTY: 'ATT管理適正在庫数',
    KOUGYOKAIBUNRUI: '工業会分類',
    INNERCD1: '内部コード1',
    INNERCD2: '内部コード2',
  },
  MITEM0011U: {
    FORM_TITLE: '品目登録',
    FORM_ID: 'MITEM0011U'
  },
};
