export const JPTEXT = {
  PROJECT_NAME: 'Project Name',
  USERID: 'User Id',
  PASSWORD: 'Password',
  CONFIRM_DIALOG_TITLE: '確認',
  SHINKI: '新規',
  SHUSEI: '修正',
  HMNO: '品目コード',
  HMNM: '品目名称',
  HMRNM: '品目略称',
  HMKBN: '品目区分',
  HMKBN_OPTIONS_1: '製品',
  HMKBN_OPTIONS_2: '仕掛品',
  HMKBN_OPTIONS_3: '材料',
  HMKBN_OPTIONS_4: '副資材',
  HMKBN_OPTIONS_5: '部品',
  SUPPCD: '仕入先コード',
  CUSTHMNM: '発注品名',
  CUSTUNIT: '発注単位コード',
  REFERENCE_SCREEN: '参照画面',
  MENU:{
    TITLE: 'Menu'
  },
  BTN_TEXT: {
    BACKTOMENU: 'メニューに戻る',
    LOGOUT: 'LogOut',
    LOGINBTN: 'Login',
    SAVEBTN: 'Save',
    RESETBTN: 'Reset',
    SEARCH: 'Search',
    CLEAR: 'Clear',
    OK: 'OK',
    CANCEL: 'Cancel',
    PREVIEW: 'Preview',
    INITIAL_DATA: 'Initial',
    DOWNLOAD: 'Download',
    EDITABLE_GRID_BUTTON: {
      SAVE: '保存',
      ADD_ROWS: '行追加',
      DELETE_ROWS: '行削除',
      COPY_ROWS: '行コピー',
      PASTE_ROWS: '行貼付',
    },
    SELECTALL: '全選択',
    YES: 'はい',
    NO: 'いいえ',
    HIDE: '非表示',
    SHOW: '表示',
    MORE: 'その他'
  },
  TOOLTIP_TEXT: {
    DELETE: '削除',
    EDIT: '編集',
    PREVIEW: '表示',
  },
  MATCH_CONDITIONS: {
    range: '〜',
    equals: 'と等しい',
    notEquals: 'と等しくない',
    startsWith: 'で始まる',
    notStartsWith: 'で始まらない',
    endsWith: 'で終わる',
    notEndsWith: 'で終わらない',
    contains: 'を含む',
    notContains: 'を含まない',
    isNull: 'が空白',
    isNotNull: 'が空白でない',
    greaterThan: 'より大きい',
    lessThan: 'より小さい',
  },
  CELL_SELECTION_OPTNS: {
    CELL_MODE: 'セルモード',
    AVERAGE: '平均',
    NUM_DATA: 'データの個数',
    NUM_VALUES: '数値の個数',
    MIN: '最小値',
    MAX: '最大値',
    SUM: '合計',
  },
  CONDITION_SETTING_DISP: {
    NAME: '名称',
    ACCESS_TYPE: '公開範囲',
    ACCESS_TYPE_OPTIONS: ['個人用', '公開用'],
    REG_USERS: '登録ユーザー ',
  },
  AUTOMATIC_HEIGHT_ADJUSTMENT_DIALOG: {
    TITLE: '高さ自動調節',
    RADIO_OPTION_YES: 'する',
    RADIO_OPTION_NO: 'しない',
  },
  HIDE_FILTERS_DAILOG:{
    TITLE: 'フィルター行表示',
    RADIO_OPTION_YES: 'する',
    RADIO_OPTION_NO: 'しない',
  },
  TABLE_OPTIONS: {
    TABLE_OPTIONS_TITLE: '表オプション',
    SAVE_AS: '名前を付けて保存',
    SORT_DATA: 'データ並替',
    SWAP_COLUMNS: '列の入替',
    SET_COLUMN_WIDTH: '列幅設定',
    ZOOM: 'ズーム',
    DISPLAY_FILTER : 'フィルター行設定',
  },
  SAVE_AS: {
    LABEL: 'ファイル名',
    DEFAULT_FILE_NAME: 'トーマス_データ',
  },
  SORT_DATA: {
    LABEL: 'データの並べ替え',
    NONE_SELECTED_OPTION: '(指定無し)',
    ASCENDING: '昇進',
    DESCENDING: '降順',
    SORT: '並べ替え',
  },
  REFERENCE_SETTING: {
    TITLE: '初期検索設定',
    LABEL: '初期検索で開く',
    RADIO_OPTION_YES: 'はい',
    RADIO_OPTION_NO: 'いいえ',
  },
  SWAP_COLUMNS: {
    DIALOG_TITLE: '列の入れ替え',
    HEADER_COLUMN: 'カラム列',
    HEADER_Display: '表示',
    HEADER_FIXED_COLUMNS: '列固定',
  },
  CELL_VALIDATIONS: {
    REQUIRED: '必要項目',
    INVALID_INPUT: '無効な入力',
  },
  DemoForm: {
    FORM_ID: 'demoform',
    FORM_TITLE: 'Demo Form',
  },
};
